# Generated by Django 3.2.2 on 2021-05-09 12:42

from django.db import migrations, models
import sakuralogin.models


class Migration(migrations.Migration):

    dependencies = [
        ('sakuralogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='discorduser',
            managers=[
                ('objects', sakuralogin.models.DiscordUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
